version: "3"

services:
  app-front:
    image: mateusob/fc3-desafio-frontend
    #build: ./frontend
    #entrypoint: ./.docker/entrypoint.sh
    container_name: desafio-fullcycle-3-frontend-app
    ports:
      - 3001:3001
    #volumes:
    #  - ./frontend:/usr/src/app
    extra_hosts: 
      - 'host.docker.internal:172.17.0.1'

  app-back:
    image: mateusob/fc3-desafio-backend
    #build: ./backend
    #entrypoint: ./.docker/entrypoint.sh
    container_name: desafio-fullcycle-3-backend-app
    ports:
      - 3000:3000
    #volumes:
    #  - ./backend:/usr/src/app
    extra_hosts: 
      - 'host.docker.internal:172.17.0.1'
