import {
  Typography,
  TableContainer,
  Table,
  TableHead,
  TableRow,
  TableBody,
  TableCell,
  Paper,
} from "@material-ui/core";
import { makeStyles } from '@material-ui/core/styles';
import Head from 'next/head'
import { Route } from "../model";
import { GetServerSideProps, NextPage } from "next";
import http from "../http";

interface RoutesListPageProps {
  routes: Route[];
}

const useStyles = makeStyles({
  table: {
    minWidth: 650,
  },
});

const RoutesListPage: NextPage<RoutesListPageProps> = ({ routes }) => {
  const classes = useStyles();

  return (
    <div>
      <Head>
        <title>Listagem de rotas</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Typography component="h1" variant="h3" color="textPrimary" gutterBottom>
        Rotas
      </Typography>
      <TableContainer component={Paper}>
      <Table className={classes.table} aria-label="caption table">
        <TableHead>
          <TableRow>
            <TableCell>Título da Rota</TableCell>
            <TableCell align="right">Latitude Origem</TableCell>
            <TableCell align="right">Longitude Origem</TableCell>
            <TableCell align="right">Latitude Destino</TableCell>
            <TableCell align="right">Longitude Destino</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {routes.map((route) => (
            <TableRow key={route.title}>
              <TableCell component="th" scope="row">
                {route.title}
              </TableCell>
              <TableCell align="right">{route.startPosition.latitude}</TableCell>
              <TableCell align="right">{route.startPosition.longitude}</TableCell>
              <TableCell align="right">{route.endPosition.latitude}</TableCell>
              <TableCell align="right">{route.endPosition.longitude}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
    </div>
  );
};

export default RoutesListPage;

export const getServerSideProps: GetServerSideProps<RoutesListPageProps> = async (context) => {
  const { data: routes } = await http.get("routes");
  console.log(routes);
  return {
    props: {
      routes,
    },
  };
};
